/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guicamrent;

/**
 *
 * @author msi thin15
 */
public class CamrentPanasonic extends javax.swing.JPanel {

    /**
     * 
     */
    public CamrentPanasonic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANASONICLUMIXS9_PIC = new javax.swing.JLabel();
        PANASONICLUMIXDCGH6_PIC = new javax.swing.JLabel();
        Camera_Label = new javax.swing.JLabel();
        PANASONICLUMIXS9_LABEL = new javax.swing.JLabel();
        RentalPANASONICLUMIXS9_LABEL = new javax.swing.JLabel();
        SPEC1PANASONICLUMIXS9_LABEL = new javax.swing.JLabel();
        SPEC2PANASONICLUMIXS9_LABEL = new javax.swing.JLabel();
        PANASONICLUMIXDCGH6_LABEL = new javax.swing.JLabel();
        RentalPANASONICLUMIXDCGH6_LABEL = new javax.swing.JLabel();
        SPEC1PANASONICLUMIXDCGH6_LABEL = new javax.swing.JLabel();
        SPEC2PANASONICLUMIXDCGH6_LABEL = new javax.swing.JLabel();
        CANONGROUP_BUTTON = new guicamrent.RoundButton_Grey();
        FUJIFILMGROUP_BUTTON = new guicamrent.RoundButton_Grey();
        RENTPANASONICLUMIXS9_BUTTON = new guicamrent.RoundButton();
        RENTPANASONICLUMIXDCGH6_BUTTON = new guicamrent.RoundButton();
        LINER1_LABEL = new javax.swing.JLabel();
        roundButton1 = new guicamrent.RoundButton();
        roundButton_Grey1 = new guicamrent.RoundButton_Grey();

        setBackground(new java.awt.Color(255, 255, 255));

        PANASONICLUMIXS9_PIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CAMPICresize/panasonic-lumix-s9.jpg"))); // NOI18N

        PANASONICLUMIXDCGH6_PIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CAMPICresize/panasonic-lumix-dc-gh6.jpg"))); // NOI18N

        Camera_Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Camera_Label.setText("Camera");

        PANASONICLUMIXS9_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        PANASONICLUMIXS9_LABEL.setText("Panasonic Lumix S9");

        RentalPANASONICLUMIXS9_LABEL.setText("Rental fee: 950 THB/day");

        SPEC1PANASONICLUMIXS9_LABEL.setText("Full-Frame sensor, 24.2MP resolution");

        SPEC2PANASONICLUMIXS9_LABEL.setText("5-axis IBIS image stabilization with 6.5 stops");

        PANASONICLUMIXDCGH6_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PANASONICLUMIXDCGH6_LABEL.setText("Panasonic Lumix DC-GH6 ");

        RentalPANASONICLUMIXDCGH6_LABEL.setText("Rental fee: 900 THB/day");

        SPEC1PANASONICLUMIXDCGH6_LABEL.setText("25MP CMOS sensor camera");

        SPEC2PANASONICLUMIXDCGH6_LABEL.setText("5.8K Full-sensor 30p, with V-Log. ");

        CANONGROUP_BUTTON.setText("Canon");
        CANONGROUP_BUTTON.addActionListener(this::CANONGROUP_BUTTONActionPerformed);

        FUJIFILMGROUP_BUTTON.setText("Fujifilm");
        FUJIFILMGROUP_BUTTON.addActionListener(this::FUJIFILMGROUP_BUTTONActionPerformed);

        RENTPANASONICLUMIXS9_BUTTON.setText("Rent");
        RENTPANASONICLUMIXS9_BUTTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RENTPANASONICLUMIXS9_BUTTONMouseClicked(evt);
            }
        });

        RENTPANASONICLUMIXDCGH6_BUTTON.setText("Rent");
        RENTPANASONICLUMIXDCGH6_BUTTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RENTPANASONICLUMIXDCGH6_BUTTONMouseClicked(evt);
            }
        });

        LINER1_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LINER1_LABEL.setText("_______________________________________");

        roundButton1.setText("Panasonic");

        roundButton_Grey1.setText("Sony");
        roundButton_Grey1.addActionListener(this::roundButton_Grey1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(roundButton_Grey1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roundButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CANONGROUP_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FUJIFILMGROUP_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Camera_Label)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PANASONICLUMIXS9_PIC)
                                .addGap(38, 38, 38)
                                .addComponent(RENTPANASONICLUMIXS9_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RentalPANASONICLUMIXS9_LABEL)
                                    .addComponent(SPEC2PANASONICLUMIXS9_LABEL)
                                    .addComponent(SPEC1PANASONICLUMIXS9_LABEL)
                                    .addComponent(PANASONICLUMIXS9_LABEL)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PANASONICLUMIXDCGH6_PIC, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(RENTPANASONICLUMIXDCGH6_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(PANASONICLUMIXDCGH6_LABEL)
                                    .addComponent(RentalPANASONICLUMIXDCGH6_LABEL)
                                    .addComponent(SPEC1PANASONICLUMIXDCGH6_LABEL)
                                    .addComponent(SPEC2PANASONICLUMIXDCGH6_LABEL))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LINER1_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Camera_Label)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FUJIFILMGROUP_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CANONGROUP_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundButton_Grey1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(PANASONICLUMIXS9_PIC, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(RENTPANASONICLUMIXS9_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PANASONICLUMIXS9_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RentalPANASONICLUMIXS9_LABEL)
                .addGap(5, 5, 5)
                .addComponent(SPEC1PANASONICLUMIXS9_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPEC2PANASONICLUMIXS9_LABEL)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(PANASONICLUMIXDCGH6_PIC, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RENTPANASONICLUMIXDCGH6_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addComponent(PANASONICLUMIXDCGH6_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RentalPANASONICLUMIXDCGH6_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPEC1PANASONICLUMIXDCGH6_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPEC2PANASONICLUMIXDCGH6_LABEL)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(LINER1_LABEL)
                    .addContainerGap(665, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CANONGROUP_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANONGROUP_BUTTONActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentCanon());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_CANONGROUP_BUTTONActionPerformed

    private void FUJIFILMGROUP_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FUJIFILMGROUP_BUTTONActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentFujiFilm());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_FUJIFILMGROUP_BUTTONActionPerformed

    private void roundButton_Grey1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton_Grey1ActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentSony());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_roundButton_Grey1ActionPerformed

    private void RENTPANASONICLUMIXS9_BUTTONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RENTPANASONICLUMIXS9_BUTTONMouseClicked
                            java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new ConfirmPanasonicLumixS9());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_RENTPANASONICLUMIXS9_BUTTONMouseClicked

    private void RENTPANASONICLUMIXDCGH6_BUTTONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RENTPANASONICLUMIXDCGH6_BUTTONMouseClicked
                                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new ConfirmPanasonicLumixDCGH6());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_RENTPANASONICLUMIXDCGH6_BUTTONMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private guicamrent.RoundButton_Grey CANONGROUP_BUTTON;
    private javax.swing.JLabel Camera_Label;
    private guicamrent.RoundButton_Grey FUJIFILMGROUP_BUTTON;
    private javax.swing.JLabel LINER1_LABEL;
    private javax.swing.JLabel PANASONICLUMIXDCGH6_LABEL;
    private javax.swing.JLabel PANASONICLUMIXDCGH6_PIC;
    private javax.swing.JLabel PANASONICLUMIXS9_LABEL;
    private javax.swing.JLabel PANASONICLUMIXS9_PIC;
    private guicamrent.RoundButton RENTPANASONICLUMIXDCGH6_BUTTON;
    private guicamrent.RoundButton RENTPANASONICLUMIXS9_BUTTON;
    private javax.swing.JLabel RentalPANASONICLUMIXDCGH6_LABEL;
    private javax.swing.JLabel RentalPANASONICLUMIXS9_LABEL;
    private javax.swing.JLabel SPEC1PANASONICLUMIXDCGH6_LABEL;
    private javax.swing.JLabel SPEC1PANASONICLUMIXS9_LABEL;
    private javax.swing.JLabel SPEC2PANASONICLUMIXDCGH6_LABEL;
    private javax.swing.JLabel SPEC2PANASONICLUMIXS9_LABEL;
    private guicamrent.RoundButton roundButton1;
    private guicamrent.RoundButton_Grey roundButton_Grey1;
    // End of variables declaration//GEN-END:variables
}
