/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guicamrent;

/**
 *
 * @author msi thin15
 */
public class CamrentFujiFilm extends javax.swing.JPanel {

    /**
     * 
     */
    public CamrentFujiFilm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FujifilmGFX100S_PIC = new javax.swing.JLabel();
        FujifilmX100VI_PIC = new javax.swing.JLabel();
        Camera_Label = new javax.swing.JLabel();
        FujifilmGFX100S_LABEL = new javax.swing.JLabel();
        RentalFujifilmGFX100S_LABEL = new javax.swing.JLabel();
        SPEC1FujifilmGFX100S_LABEL = new javax.swing.JLabel();
        SPEC2FujifilmGFX100S_LABEL = new javax.swing.JLabel();
        FujifilmX100VI_LABEL = new javax.swing.JLabel();
        RentalFujifilmX100VI_LABEL = new javax.swing.JLabel();
        SPEC1FujifilmX100VI_LABEL = new javax.swing.JLabel();
        SPEC2FujifilmX100VI_LABEL = new javax.swing.JLabel();
        RENTPANASONICLUMIXS9_BUTTON = new guicamrent.RoundButton();
        RENTPANASONICLUMIXDCGH6_BUTTON = new guicamrent.RoundButton();
        LINER1_LABEL = new javax.swing.JLabel();
        roundButton_Grey1 = new guicamrent.RoundButton_Grey();
        roundButton_Grey2 = new guicamrent.RoundButton_Grey();
        roundButton_Grey3 = new guicamrent.RoundButton_Grey();
        roundButton1 = new guicamrent.RoundButton();

        setBackground(new java.awt.Color(255, 255, 255));

        FujifilmGFX100S_PIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CAMPICresize/gfx-100s.jpg"))); // NOI18N

        FujifilmX100VI_PIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CAMPICresize/fujifilm-x100-vi.jpg"))); // NOI18N

        Camera_Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Camera_Label.setText("Camera");

        FujifilmGFX100S_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        FujifilmGFX100S_LABEL.setText("Fujifilm GFX 100S");

        RentalFujifilmGFX100S_LABEL.setText("Rental fee: 1,900 THB/day ");

        SPEC1FujifilmGFX100S_LABEL.setText("Medium format camera with 102MP 43.8 x ");

        SPEC2FujifilmGFX100S_LABEL.setText("32.9mm BSI CMOS sensor");

        FujifilmX100VI_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        FujifilmX100VI_LABEL.setText("Fujifilm X100 VI");

        RentalFujifilmX100VI_LABEL.setText("Rental fee: 1,000 THB/day");

        SPEC1FujifilmX100VI_LABEL.setText("Camera with 23mm F2 lens, X-Trans CMOS 5 HR ");

        SPEC2FujifilmX100VI_LABEL.setText("sensor, 40.2 megapixel resolution, and Film ");

        RENTPANASONICLUMIXS9_BUTTON.setText("Rent");
        RENTPANASONICLUMIXS9_BUTTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RENTPANASONICLUMIXS9_BUTTONMouseClicked(evt);
            }
        });

        RENTPANASONICLUMIXDCGH6_BUTTON.setText("Rent");
        RENTPANASONICLUMIXDCGH6_BUTTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RENTPANASONICLUMIXDCGH6_BUTTONMouseClicked(evt);
            }
        });

        LINER1_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LINER1_LABEL.setText("_________________________________________________");

        roundButton_Grey1.setText("Sony");
        roundButton_Grey1.addActionListener(this::roundButton_Grey1ActionPerformed);

        roundButton_Grey2.setText("Panasonic");
        roundButton_Grey2.addActionListener(this::roundButton_Grey2ActionPerformed);

        roundButton_Grey3.setText("Canon");
        roundButton_Grey3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roundButton_Grey3MouseClicked(evt);
            }
        });

        roundButton1.setText("Fujifilm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Camera_Label)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RentalFujifilmGFX100S_LABEL)
                            .addComponent(SPEC2FujifilmGFX100S_LABEL)
                            .addComponent(SPEC1FujifilmGFX100S_LABEL)
                            .addComponent(FujifilmGFX100S_LABEL)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FujifilmX100VI_PIC, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RENTPANASONICLUMIXDCGH6_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(FujifilmX100VI_LABEL)
                            .addComponent(RentalFujifilmX100VI_LABEL)
                            .addComponent(SPEC1FujifilmX100VI_LABEL)
                            .addComponent(SPEC2FujifilmX100VI_LABEL)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(roundButton_Grey1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roundButton_Grey2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(FujifilmGFX100S_PIC))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(RENTPANASONICLUMIXS9_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roundButton_Grey3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roundButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LINER1_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Camera_Label)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roundButton_Grey1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundButton_Grey2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundButton_Grey3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(FujifilmGFX100S_PIC, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(RENTPANASONICLUMIXS9_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FujifilmGFX100S_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RentalFujifilmGFX100S_LABEL)
                .addGap(5, 5, 5)
                .addComponent(SPEC1FujifilmGFX100S_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPEC2FujifilmGFX100S_LABEL)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(FujifilmX100VI_PIC, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RENTPANASONICLUMIXDCGH6_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addComponent(FujifilmX100VI_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RentalFujifilmX100VI_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPEC1FujifilmX100VI_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPEC2FujifilmX100VI_LABEL)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(LINER1_LABEL)
                    .addContainerGap(667, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void roundButton_Grey1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton_Grey1ActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentSony());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_roundButton_Grey1ActionPerformed

    private void roundButton_Grey2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton_Grey2ActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentPanasonic());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_roundButton_Grey2ActionPerformed

    private void roundButton_Grey3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundButton_Grey3MouseClicked
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentCanon());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_roundButton_Grey3MouseClicked

    private void RENTPANASONICLUMIXS9_BUTTONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RENTPANASONICLUMIXS9_BUTTONMouseClicked
                                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new ConfirmFujiFilmGFX100s());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_RENTPANASONICLUMIXS9_BUTTONMouseClicked

    private void RENTPANASONICLUMIXDCGH6_BUTTONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RENTPANASONICLUMIXDCGH6_BUTTONMouseClicked
                                            java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new ConfirmFujiFilmX100VI());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_RENTPANASONICLUMIXDCGH6_BUTTONMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Camera_Label;
    private javax.swing.JLabel FujifilmGFX100S_LABEL;
    private javax.swing.JLabel FujifilmGFX100S_PIC;
    private javax.swing.JLabel FujifilmX100VI_LABEL;
    private javax.swing.JLabel FujifilmX100VI_PIC;
    private javax.swing.JLabel LINER1_LABEL;
    private guicamrent.RoundButton RENTPANASONICLUMIXDCGH6_BUTTON;
    private guicamrent.RoundButton RENTPANASONICLUMIXS9_BUTTON;
    private javax.swing.JLabel RentalFujifilmGFX100S_LABEL;
    private javax.swing.JLabel RentalFujifilmX100VI_LABEL;
    private javax.swing.JLabel SPEC1FujifilmGFX100S_LABEL;
    private javax.swing.JLabel SPEC1FujifilmX100VI_LABEL;
    private javax.swing.JLabel SPEC2FujifilmGFX100S_LABEL;
    private javax.swing.JLabel SPEC2FujifilmX100VI_LABEL;
    private guicamrent.RoundButton roundButton1;
    private guicamrent.RoundButton_Grey roundButton_Grey1;
    private guicamrent.RoundButton_Grey roundButton_Grey2;
    private guicamrent.RoundButton_Grey roundButton_Grey3;
    // End of variables declaration//GEN-END:variables
}
