/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guicamrent;

/**
 *
 * @author msi thin15
 */
public class CamrentSony extends javax.swing.JPanel {

    /**
     * 
     */
    public CamrentSony() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SonyA7V_PIC = new javax.swing.JLabel();
        SONYZVE10_PIC = new javax.swing.JLabel();
        Camera_Label = new javax.swing.JLabel();
        SONYA7V_LABEL = new javax.swing.JLabel();
        RentalSonyA7V_LABEL = new javax.swing.JLabel();
        SPEC1SONYA7V_LABEL = new javax.swing.JLabel();
        SPEC2SONYA7V_LABEL = new javax.swing.JLabel();
        SONYZVE10_LABEL = new javax.swing.JLabel();
        RentalSonyZVE10_LABEL = new javax.swing.JLabel();
        SPEC1SONYZVE10_LABEL = new javax.swing.JLabel();
        SPEC2SONYZVE10_LABEL = new javax.swing.JLabel();
        SONYGROUP_BUTTON = new guicamrent.RoundButton();
        PANASONICGROUP_BUTTON = new guicamrent.RoundButton_Grey();
        CANONGROUP_BUTTON = new guicamrent.RoundButton_Grey();
        FUJIFILMGROUP_BUTTON = new guicamrent.RoundButton_Grey();
        RENTSONYA7V_BUTTON = new guicamrent.RoundButton();
        RENTSONYZVE10_BUTTON = new guicamrent.RoundButton();
        LINER1_LABEL = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        SonyA7V_PIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CAMPICresize/sony-a7v.jpg"))); // NOI18N

        SONYZVE10_PIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CAMPICresize/sony-zv-e10.jpg"))); // NOI18N

        Camera_Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Camera_Label.setText("Camera");

        SONYA7V_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        SONYA7V_LABEL.setText("Sony A7V");

        RentalSonyA7V_LABEL.setText("Rental fee: 1,400 THB/day");

        SPEC1SONYA7V_LABEL.setText("35mm full-frame camera, 33MP ");

        SPEC2SONYA7V_LABEL.setText("Partially-Stacked Exmor RS Sensor, AI ");

        SONYZVE10_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SONYZVE10_LABEL.setText("Sony ZV-E10 + Lens ");

        RentalSonyZVE10_LABEL.setText("Rental fee 500 THB/day");

        SPEC1SONYZVE10_LABEL.setText("24.2 million pixel APS-C Mirrorless Camera");

        SPEC2SONYZVE10_LABEL.setText("Realtime Eye AF Focus System and 4k Video.");

        SONYGROUP_BUTTON.setText("Sony");
        SONYGROUP_BUTTON.addActionListener(this::SONYGROUP_BUTTONActionPerformed);

        PANASONICGROUP_BUTTON.setText("Panasonic");
        PANASONICGROUP_BUTTON.addActionListener(this::PANASONICGROUP_BUTTONActionPerformed);

        CANONGROUP_BUTTON.setText("Canon");
        CANONGROUP_BUTTON.addActionListener(this::CANONGROUP_BUTTONActionPerformed);

        FUJIFILMGROUP_BUTTON.setText("Fujifilm");
        FUJIFILMGROUP_BUTTON.addActionListener(this::FUJIFILMGROUP_BUTTONActionPerformed);

        RENTSONYA7V_BUTTON.setText("Rent");
        RENTSONYA7V_BUTTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RENTSONYA7V_BUTTONMouseClicked(evt);
            }
        });

        RENTSONYZVE10_BUTTON.setText("Rent");
        RENTSONYZVE10_BUTTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RENTSONYZVE10_BUTTONMouseClicked(evt);
            }
        });

        LINER1_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LINER1_LABEL.setText("_______________________________________");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SONYGROUP_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PANASONICGROUP_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CANONGROUP_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FUJIFILMGROUP_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Camera_Label)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SonyA7V_PIC)
                                .addGap(38, 38, 38)
                                .addComponent(RENTSONYA7V_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RentalSonyA7V_LABEL)
                                    .addComponent(SPEC2SONYA7V_LABEL)
                                    .addComponent(SPEC1SONYA7V_LABEL)
                                    .addComponent(SONYA7V_LABEL)
                                    .addComponent(SONYZVE10_LABEL)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SONYZVE10_PIC, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(RENTSONYZVE10_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(RentalSonyZVE10_LABEL)
                                    .addComponent(SPEC1SONYZVE10_LABEL)
                                    .addComponent(SPEC2SONYZVE10_LABEL))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LINER1_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Camera_Label)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PANASONICGROUP_BUTTON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SONYGROUP_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FUJIFILMGROUP_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CANONGROUP_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addComponent(SonyA7V_PIC, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(RENTSONYA7V_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SONYA7V_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RentalSonyA7V_LABEL)
                .addGap(5, 5, 5)
                .addComponent(SPEC1SONYA7V_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPEC2SONYA7V_LABEL)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(SONYZVE10_PIC, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RENTSONYZVE10_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addComponent(SONYZVE10_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RentalSonyZVE10_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPEC1SONYZVE10_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPEC2SONYZVE10_LABEL)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(LINER1_LABEL)
                    .addContainerGap(665, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SONYGROUP_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SONYGROUP_BUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SONYGROUP_BUTTONActionPerformed

    private void PANASONICGROUP_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PANASONICGROUP_BUTTONActionPerformed
            java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentPanasonic());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_PANASONICGROUP_BUTTONActionPerformed

    private void CANONGROUP_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANONGROUP_BUTTONActionPerformed
            java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentCanon());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_CANONGROUP_BUTTONActionPerformed

    private void FUJIFILMGROUP_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FUJIFILMGROUP_BUTTONActionPerformed
            java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentFujiFilm());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_FUJIFILMGROUP_BUTTONActionPerformed

    private void RENTSONYA7V_BUTTONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RENTSONYA7V_BUTTONMouseClicked
            java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new ConfirmSonyA7V());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_RENTSONYA7V_BUTTONMouseClicked

    private void RENTSONYZVE10_BUTTONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RENTSONYZVE10_BUTTONMouseClicked
            java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new ConfirmSonyZVE10());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_RENTSONYZVE10_BUTTONMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private guicamrent.RoundButton_Grey CANONGROUP_BUTTON;
    private javax.swing.JLabel Camera_Label;
    private guicamrent.RoundButton_Grey FUJIFILMGROUP_BUTTON;
    private javax.swing.JLabel LINER1_LABEL;
    private guicamrent.RoundButton_Grey PANASONICGROUP_BUTTON;
    private guicamrent.RoundButton RENTSONYA7V_BUTTON;
    private guicamrent.RoundButton RENTSONYZVE10_BUTTON;
    private javax.swing.JLabel RentalSonyA7V_LABEL;
    private javax.swing.JLabel RentalSonyZVE10_LABEL;
    private javax.swing.JLabel SONYA7V_LABEL;
    private guicamrent.RoundButton SONYGROUP_BUTTON;
    private javax.swing.JLabel SONYZVE10_LABEL;
    private javax.swing.JLabel SONYZVE10_PIC;
    private javax.swing.JLabel SPEC1SONYA7V_LABEL;
    private javax.swing.JLabel SPEC1SONYZVE10_LABEL;
    private javax.swing.JLabel SPEC2SONYA7V_LABEL;
    private javax.swing.JLabel SPEC2SONYZVE10_LABEL;
    private javax.swing.JLabel SonyA7V_PIC;
    // End of variables declaration//GEN-END:variables
}
