/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guicamrent;

/**
 *
 * @author msi thin15
 */
public class CamrentCanon extends javax.swing.JPanel {

    /**
     * 
     */
    public CamrentCanon() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CANONEOSR6MARKII_PIC = new javax.swing.JLabel();
        CANONIXUS285HSA_PIC = new javax.swing.JLabel();
        Camera_Label = new javax.swing.JLabel();
        CANONEOSR6MARKII_LABEL = new javax.swing.JLabel();
        RentalCANONEOSR6MARKII_LABEL = new javax.swing.JLabel();
        SPEC1CANONEOSR6MARKI_LABEL = new javax.swing.JLabel();
        SPEC2CANONEOSR6MARKI_LABEL = new javax.swing.JLabel();
        CANONIXUS285HSA_LABEL = new javax.swing.JLabel();
        RentalCANONIXUS285HSA_LABEL = new javax.swing.JLabel();
        SPEC1CANONIXUS285HSA_LABEL1 = new javax.swing.JLabel();
        SPEC2CANONIXUS285HSA_LABEL = new javax.swing.JLabel();
        FUJIFILMGROUP_BUTTON = new guicamrent.RoundButton_Grey();
        RENTPANASONICLUMIXS9_BUTTON = new guicamrent.RoundButton();
        RENTPANASONICLUMIXDCGH6_BUTTON = new guicamrent.RoundButton();
        LINER1_LABEL = new javax.swing.JLabel();
        roundButton_Grey1 = new guicamrent.RoundButton_Grey();
        roundButton2 = new guicamrent.RoundButton();
        roundButton_Grey2 = new guicamrent.RoundButton_Grey();

        setBackground(new java.awt.Color(255, 255, 255));

        CANONEOSR6MARKII_PIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CAMPICresize/canon-r6-mkii.jpg"))); // NOI18N

        CANONIXUS285HSA_PIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CAMPICresize/canon-ixus-285-hs-a-silver.jpg"))); // NOI18N

        Camera_Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Camera_Label.setText("Camera");

        CANONEOSR6MARKII_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        CANONEOSR6MARKII_LABEL.setText("Canon EOS R6 Mark II");

        RentalCANONEOSR6MARKII_LABEL.setText("Rental fee: 1,300 THB/day");

        SPEC1CANONEOSR6MARKI_LABEL.setText("24.2MP Full-Frame CMOS sensor");

        SPEC2CANONEOSR6MARKI_LABEL.setText("4K60 10-bit internal video recording and C-Log 3");

        CANONIXUS285HSA_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CANONIXUS285HSA_LABEL.setText("Canon IXUS 285 HS A");

        RentalCANONIXUS285HSA_LABEL.setText("Rental fee: 400 THB/day");

        SPEC1CANONIXUS285HSA_LABEL1.setText("20.2-megapixel CMOS sensor");

        SPEC2CANONIXUS285HSA_LABEL.setText("25–300mm focal length");

        FUJIFILMGROUP_BUTTON.setText("Fujifilm");
        FUJIFILMGROUP_BUTTON.addActionListener(this::FUJIFILMGROUP_BUTTONActionPerformed);

        RENTPANASONICLUMIXS9_BUTTON.setText("Rent");
        RENTPANASONICLUMIXS9_BUTTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RENTPANASONICLUMIXS9_BUTTONMouseClicked(evt);
            }
        });

        RENTPANASONICLUMIXDCGH6_BUTTON.setText("Rent");
        RENTPANASONICLUMIXDCGH6_BUTTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RENTPANASONICLUMIXDCGH6_BUTTONMouseClicked(evt);
            }
        });

        LINER1_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LINER1_LABEL.setText("_________________________________________________");

        roundButton_Grey1.setText("Sony");
        roundButton_Grey1.addActionListener(this::roundButton_Grey1ActionPerformed);

        roundButton2.setText("Canon");

        roundButton_Grey2.setText("Panasonic");
        roundButton_Grey2.addActionListener(this::roundButton_Grey2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Camera_Label)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RentalCANONEOSR6MARKII_LABEL)
                            .addComponent(SPEC2CANONEOSR6MARKI_LABEL)
                            .addComponent(SPEC1CANONEOSR6MARKI_LABEL)
                            .addComponent(CANONEOSR6MARKII_LABEL)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CANONIXUS285HSA_PIC, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RENTPANASONICLUMIXDCGH6_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CANONIXUS285HSA_LABEL)
                            .addComponent(RentalCANONIXUS285HSA_LABEL)
                            .addComponent(SPEC2CANONIXUS285HSA_LABEL)
                            .addComponent(SPEC1CANONIXUS285HSA_LABEL1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(roundButton_Grey1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roundButton_Grey2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(CANONEOSR6MARKII_PIC))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(RENTPANASONICLUMIXS9_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roundButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FUJIFILMGROUP_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LINER1_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Camera_Label)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FUJIFILMGROUP_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundButton_Grey1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundButton_Grey2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(CANONEOSR6MARKII_PIC, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(RENTPANASONICLUMIXS9_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CANONEOSR6MARKII_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RentalCANONEOSR6MARKII_LABEL)
                .addGap(5, 5, 5)
                .addComponent(SPEC1CANONEOSR6MARKI_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPEC2CANONEOSR6MARKI_LABEL)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(CANONIXUS285HSA_PIC, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RENTPANASONICLUMIXDCGH6_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addComponent(CANONIXUS285HSA_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RentalCANONIXUS285HSA_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPEC1CANONIXUS285HSA_LABEL1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPEC2CANONIXUS285HSA_LABEL)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(LINER1_LABEL)
                    .addContainerGap(667, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FUJIFILMGROUP_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FUJIFILMGROUP_BUTTONActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentFujiFilm());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_FUJIFILMGROUP_BUTTONActionPerformed

    private void roundButton_Grey1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton_Grey1ActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentSony());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_roundButton_Grey1ActionPerformed

    private void roundButton_Grey2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton_Grey2ActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentPanasonic());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_roundButton_Grey2ActionPerformed

    private void RENTPANASONICLUMIXS9_BUTTONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RENTPANASONICLUMIXS9_BUTTONMouseClicked
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new ConfirmCanonEOSR6MarkII());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_RENTPANASONICLUMIXS9_BUTTONMouseClicked

    private void RENTPANASONICLUMIXDCGH6_BUTTONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RENTPANASONICLUMIXDCGH6_BUTTONMouseClicked
                            java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new ConfirmCanonIXUS285HSA());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_RENTPANASONICLUMIXDCGH6_BUTTONMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CANONEOSR6MARKII_LABEL;
    private javax.swing.JLabel CANONEOSR6MARKII_PIC;
    private javax.swing.JLabel CANONIXUS285HSA_LABEL;
    private javax.swing.JLabel CANONIXUS285HSA_PIC;
    private javax.swing.JLabel Camera_Label;
    private guicamrent.RoundButton_Grey FUJIFILMGROUP_BUTTON;
    private javax.swing.JLabel LINER1_LABEL;
    private guicamrent.RoundButton RENTPANASONICLUMIXDCGH6_BUTTON;
    private guicamrent.RoundButton RENTPANASONICLUMIXS9_BUTTON;
    private javax.swing.JLabel RentalCANONEOSR6MARKII_LABEL;
    private javax.swing.JLabel RentalCANONIXUS285HSA_LABEL;
    private javax.swing.JLabel SPEC1CANONEOSR6MARKI_LABEL;
    private javax.swing.JLabel SPEC1CANONIXUS285HSA_LABEL1;
    private javax.swing.JLabel SPEC2CANONEOSR6MARKI_LABEL;
    private javax.swing.JLabel SPEC2CANONIXUS285HSA_LABEL;
    private guicamrent.RoundButton roundButton2;
    private guicamrent.RoundButton_Grey roundButton_Grey1;
    private guicamrent.RoundButton_Grey roundButton_Grey2;
    // End of variables declaration//GEN-END:variables
}
