/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guicamrent;

/**
 *
 * @author natth
 */
public class ConfirmCanonIXUS285HSA extends javax.swing.JPanel {

    /**
     * Creates new form ConfirmFujiFilmGFX100s
     */
    public ConfirmCanonIXUS285HSA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackToCanon_BUTTON = new guicamrent.RoundButton();
        CanonIXUS285HSA_PIC = new javax.swing.JLabel();
        CanonIXUS285HSA_LABEL = new javax.swing.JLabel();
        StatusCanonIXUS285HSA_TEXTFIELD = new guicamrent.RoundTextField();
        PriceCanonIXUS285HSA_LABEL = new javax.swing.JLabel();
        Spec1CanonIXUS285HSA_LABEL = new javax.swing.JLabel();
        Spec2CanonIXUS285HSA_LABEL = new javax.swing.JLabel();
        ConfirmPriceCanonIXUS285HSA_LABEL = new javax.swing.JLabel();
        ConfirmPrice_LABEL = new javax.swing.JLabel();
        ConfirmDayCanonIXUS285HSA_LABEL = new javax.swing.JLabel();
        DayCanonIXUS285HSA_LABEL = new javax.swing.JLabel();
        TotalCanonIXUS285HSA_LABEL = new javax.swing.JLabel();
        RealTotalCanonIXUS285HSA_LABEL = new javax.swing.JLabel();
        ConfirmRentCanonIXUS285HSA_BUTTON = new guicamrent.RoundButton();

        setBackground(new java.awt.Color(255, 255, 255));

        BackToCanon_BUTTON.setText("←");
        BackToCanon_BUTTON.addActionListener(this::BackToCanon_BUTTONActionPerformed);

        CanonIXUS285HSA_PIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CAMPICresize/canon-ixus-285-hs-a-silver.jpg"))); // NOI18N

        CanonIXUS285HSA_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CanonIXUS285HSA_LABEL.setText("Canon IXUS 285 HS A");

        StatusCanonIXUS285HSA_TEXTFIELD.setEditable(false);
        StatusCanonIXUS285HSA_TEXTFIELD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StatusCanonIXUS285HSA_TEXTFIELD.setText("avaliable");
        StatusCanonIXUS285HSA_TEXTFIELD.addActionListener(this::StatusCanonIXUS285HSA_TEXTFIELDActionPerformed);

        PriceCanonIXUS285HSA_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        PriceCanonIXUS285HSA_LABEL.setText("400 THB /day");

        Spec1CanonIXUS285HSA_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Spec1CanonIXUS285HSA_LABEL.setText("Compact digital camera with a 20.2-megapixel ");

        Spec2CanonIXUS285HSA_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Spec2CanonIXUS285HSA_LABEL.setText("CMOS sensor and a 25–300mm focal length.");

        ConfirmPriceCanonIXUS285HSA_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmPriceCanonIXUS285HSA_LABEL.setText("Price per day");

        ConfirmPrice_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmPrice_LABEL.setText("400 THB");

        ConfirmDayCanonIXUS285HSA_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmDayCanonIXUS285HSA_LABEL.setText("number of days");

        DayCanonIXUS285HSA_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DayCanonIXUS285HSA_LABEL.setText("1 day");

        TotalCanonIXUS285HSA_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TotalCanonIXUS285HSA_LABEL.setText("Total");

        RealTotalCanonIXUS285HSA_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RealTotalCanonIXUS285HSA_LABEL.setText("400 THB");

        ConfirmRentCanonIXUS285HSA_BUTTON.setText("Confirm rental");
        ConfirmRentCanonIXUS285HSA_BUTTON.addActionListener(this::ConfirmRentCanonIXUS285HSA_BUTTONActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackToCanon_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ConfirmPriceCanonIXUS285HSA_LABEL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalCanonIXUS285HSA_LABEL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ConfirmDayCanonIXUS285HSA_LABEL, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RealTotalCanonIXUS285HSA_LABEL)
                                    .addComponent(DayCanonIXUS285HSA_LABEL)
                                    .addComponent(ConfirmPrice_LABEL))
                                .addGap(30, 30, 30))
                            .addComponent(Spec2CanonIXUS285HSA_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PriceCanonIXUS285HSA_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(ConfirmRentCanonIXUS285HSA_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Spec1CanonIXUS285HSA_LABEL)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CanonIXUS285HSA_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(StatusCanonIXUS285HSA_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(8, 8, 8))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(CanonIXUS285HSA_PIC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackToCanon_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CanonIXUS285HSA_PIC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CanonIXUS285HSA_LABEL)
                    .addComponent(StatusCanonIXUS285HSA_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PriceCanonIXUS285HSA_LABEL)
                .addGap(28, 28, 28)
                .addComponent(Spec1CanonIXUS285HSA_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Spec2CanonIXUS285HSA_LABEL)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPriceCanonIXUS285HSA_LABEL)
                    .addComponent(ConfirmPrice_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmDayCanonIXUS285HSA_LABEL)
                    .addComponent(DayCanonIXUS285HSA_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalCanonIXUS285HSA_LABEL)
                    .addComponent(RealTotalCanonIXUS285HSA_LABEL))
                .addGap(53, 53, 53)
                .addComponent(ConfirmRentCanonIXUS285HSA_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackToCanon_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToCanon_BUTTONActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentCanon());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_BackToCanon_BUTTONActionPerformed

    private void StatusCanonIXUS285HSA_TEXTFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusCanonIXUS285HSA_TEXTFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusCanonIXUS285HSA_TEXTFIELDActionPerformed

    private void ConfirmRentCanonIXUS285HSA_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmRentCanonIXUS285HSA_BUTTONActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new ConfirmRent());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_ConfirmRentCanonIXUS285HSA_BUTTONActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private guicamrent.RoundButton BackToCanon_BUTTON;
    private javax.swing.JLabel CanonIXUS285HSA_LABEL;
    private javax.swing.JLabel CanonIXUS285HSA_PIC;
    private javax.swing.JLabel ConfirmDayCanonIXUS285HSA_LABEL;
    private javax.swing.JLabel ConfirmPriceCanonIXUS285HSA_LABEL;
    private javax.swing.JLabel ConfirmPrice_LABEL;
    private guicamrent.RoundButton ConfirmRentCanonIXUS285HSA_BUTTON;
    private javax.swing.JLabel DayCanonIXUS285HSA_LABEL;
    private javax.swing.JLabel PriceCanonIXUS285HSA_LABEL;
    private javax.swing.JLabel RealTotalCanonIXUS285HSA_LABEL;
    private javax.swing.JLabel Spec1CanonIXUS285HSA_LABEL;
    private javax.swing.JLabel Spec2CanonIXUS285HSA_LABEL;
    private guicamrent.RoundTextField StatusCanonIXUS285HSA_TEXTFIELD;
    private javax.swing.JLabel TotalCanonIXUS285HSA_LABEL;
    // End of variables declaration//GEN-END:variables
}
