/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guicamrent;

/**
 *
 * @author natth
 */
public class ConfirmPanasonicLumixDCGH6 extends javax.swing.JPanel {

    /**
     * Creates new form ConfirmFujiFilmGFX100s
     */
    public ConfirmPanasonicLumixDCGH6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackToPanasonic_BUTTON = new guicamrent.RoundButton();
        PanasonicLumixDCGH6_PIC = new javax.swing.JLabel();
        PanasonicLumixDCGH6_LABEL = new javax.swing.JLabel();
        StatusPanasonicLumixDCGH6_TEXTFIELD = new guicamrent.RoundTextField();
        PricePanasonicLumixDCGH6_LABEL = new javax.swing.JLabel();
        Spec1PanasonicLumixDCGH6_LABEL = new javax.swing.JLabel();
        Spec2PanasonicLumixDCGH6_LABEL = new javax.swing.JLabel();
        ConfirmPricePanasonicLumixDCGH6_LABEL = new javax.swing.JLabel();
        ConfirmPrice_LABEL = new javax.swing.JLabel();
        ConfirmDayPanasonicLumixDCGH6_LABEL = new javax.swing.JLabel();
        DayPanasonicLumixDCGH6_LABEL = new javax.swing.JLabel();
        TotalPanasonicLumixDCGH6_LABEL = new javax.swing.JLabel();
        RealTotalPanasonicLumixDCGH6_LABEL = new javax.swing.JLabel();
        ConfirmRentPanasonicLumixDCGH6_BUTTON = new guicamrent.RoundButton();

        setBackground(new java.awt.Color(255, 255, 255));

        BackToPanasonic_BUTTON.setText("←");
        BackToPanasonic_BUTTON.addActionListener(this::BackToPanasonic_BUTTONActionPerformed);

        PanasonicLumixDCGH6_PIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CAMPICresize/panasonic-lumix-dc-gh6.jpg"))); // NOI18N

        PanasonicLumixDCGH6_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PanasonicLumixDCGH6_LABEL.setText("Panasonic Lumix DC-GH6 ");

        StatusPanasonicLumixDCGH6_TEXTFIELD.setEditable(false);
        StatusPanasonicLumixDCGH6_TEXTFIELD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StatusPanasonicLumixDCGH6_TEXTFIELD.setText("avaliable");
        StatusPanasonicLumixDCGH6_TEXTFIELD.addActionListener(this::StatusPanasonicLumixDCGH6_TEXTFIELDActionPerformed);

        PricePanasonicLumixDCGH6_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        PricePanasonicLumixDCGH6_LABEL.setText("900 THB /day");

        Spec1PanasonicLumixDCGH6_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Spec1PanasonicLumixDCGH6_LABEL.setText("25MP CMOS sensor camera");

        Spec2PanasonicLumixDCGH6_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Spec2PanasonicLumixDCGH6_LABEL.setText("5.8K Full-sensor 30p, with V-Log. ");

        ConfirmPricePanasonicLumixDCGH6_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmPricePanasonicLumixDCGH6_LABEL.setText("Price per day");

        ConfirmPrice_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmPrice_LABEL.setText("900 THB");

        ConfirmDayPanasonicLumixDCGH6_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmDayPanasonicLumixDCGH6_LABEL.setText("number of days");

        DayPanasonicLumixDCGH6_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DayPanasonicLumixDCGH6_LABEL.setText("1 day");

        TotalPanasonicLumixDCGH6_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TotalPanasonicLumixDCGH6_LABEL.setText("Total");

        RealTotalPanasonicLumixDCGH6_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RealTotalPanasonicLumixDCGH6_LABEL.setText("900 THB");

        ConfirmRentPanasonicLumixDCGH6_BUTTON.setText("Confirm rental");
        ConfirmRentPanasonicLumixDCGH6_BUTTON.addActionListener(this::ConfirmRentPanasonicLumixDCGH6_BUTTONActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackToPanasonic_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ConfirmPricePanasonicLumixDCGH6_LABEL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalPanasonicLumixDCGH6_LABEL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ConfirmDayPanasonicLumixDCGH6_LABEL, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RealTotalPanasonicLumixDCGH6_LABEL)
                                    .addComponent(DayPanasonicLumixDCGH6_LABEL)
                                    .addComponent(ConfirmPrice_LABEL))
                                .addGap(30, 30, 30))
                            .addComponent(Spec2PanasonicLumixDCGH6_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PricePanasonicLumixDCGH6_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(ConfirmRentPanasonicLumixDCGH6_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Spec1PanasonicLumixDCGH6_LABEL)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PanasonicLumixDCGH6_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(StatusPanasonicLumixDCGH6_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(8, 8, 8))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(PanasonicLumixDCGH6_PIC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackToPanasonic_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanasonicLumixDCGH6_PIC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PanasonicLumixDCGH6_LABEL)
                    .addComponent(StatusPanasonicLumixDCGH6_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PricePanasonicLumixDCGH6_LABEL)
                .addGap(28, 28, 28)
                .addComponent(Spec1PanasonicLumixDCGH6_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Spec2PanasonicLumixDCGH6_LABEL)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPricePanasonicLumixDCGH6_LABEL)
                    .addComponent(ConfirmPrice_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmDayPanasonicLumixDCGH6_LABEL)
                    .addComponent(DayPanasonicLumixDCGH6_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalPanasonicLumixDCGH6_LABEL)
                    .addComponent(RealTotalPanasonicLumixDCGH6_LABEL))
                .addGap(53, 53, 53)
                .addComponent(ConfirmRentPanasonicLumixDCGH6_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackToPanasonic_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToPanasonic_BUTTONActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentPanasonic());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_BackToPanasonic_BUTTONActionPerformed

    private void StatusPanasonicLumixDCGH6_TEXTFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusPanasonicLumixDCGH6_TEXTFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusPanasonicLumixDCGH6_TEXTFIELDActionPerformed

    private void ConfirmRentPanasonicLumixDCGH6_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmRentPanasonicLumixDCGH6_BUTTONActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new ConfirmRent());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_ConfirmRentPanasonicLumixDCGH6_BUTTONActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private guicamrent.RoundButton BackToPanasonic_BUTTON;
    private javax.swing.JLabel ConfirmDayPanasonicLumixDCGH6_LABEL;
    private javax.swing.JLabel ConfirmPricePanasonicLumixDCGH6_LABEL;
    private javax.swing.JLabel ConfirmPrice_LABEL;
    private guicamrent.RoundButton ConfirmRentPanasonicLumixDCGH6_BUTTON;
    private javax.swing.JLabel DayPanasonicLumixDCGH6_LABEL;
    private javax.swing.JLabel PanasonicLumixDCGH6_LABEL;
    private javax.swing.JLabel PanasonicLumixDCGH6_PIC;
    private javax.swing.JLabel PricePanasonicLumixDCGH6_LABEL;
    private javax.swing.JLabel RealTotalPanasonicLumixDCGH6_LABEL;
    private javax.swing.JLabel Spec1PanasonicLumixDCGH6_LABEL;
    private javax.swing.JLabel Spec2PanasonicLumixDCGH6_LABEL;
    private guicamrent.RoundTextField StatusPanasonicLumixDCGH6_TEXTFIELD;
    private javax.swing.JLabel TotalPanasonicLumixDCGH6_LABEL;
    // End of variables declaration//GEN-END:variables
}
