/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guicamrent;

/**
 *
 * @author natth
 */
public class ConfirmFujiFilmX100VI extends javax.swing.JPanel {

    /**
     * Creates new form ConfirmFujiFilmGFX100s
     */
    public ConfirmFujiFilmX100VI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BacktToFujifilm_BUTTON = new guicamrent.RoundButton();
        FujifilmX100VI_PIC = new javax.swing.JLabel();
        FujifilmX100VI_LABEL = new javax.swing.JLabel();
        StatusFujifilmX100VI_TEXTFIELD = new guicamrent.RoundTextField();
        PriceFujifilmX100VI_LABEL = new javax.swing.JLabel();
        Spec1FujifilmX100VI_LABEL = new javax.swing.JLabel();
        Spec2FujifilmX100VI_LABEL = new javax.swing.JLabel();
        ConfirmPriceFujifilmX100VI_LABEL = new javax.swing.JLabel();
        ConfirmPrice_LABEL = new javax.swing.JLabel();
        ConfirmDayFujifilmX100VI_LABEL = new javax.swing.JLabel();
        DayFujifilmX100VI_LABEL = new javax.swing.JLabel();
        TotalFujifilmX100VI_LABEL = new javax.swing.JLabel();
        RealTotalFujifilmX100VI_LABEL = new javax.swing.JLabel();
        ConfirmRentFujifilmX100VI_BUTTON = new guicamrent.RoundButton();

        setBackground(new java.awt.Color(255, 255, 255));

        BacktToFujifilm_BUTTON.setText("←");
        BacktToFujifilm_BUTTON.addActionListener(this::BacktToFujifilm_BUTTONActionPerformed);

        FujifilmX100VI_PIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CAMPICresize/fujifilm-x100-vi.jpg"))); // NOI18N

        FujifilmX100VI_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        FujifilmX100VI_LABEL.setText("Fujifilm X 100 VI");

        StatusFujifilmX100VI_TEXTFIELD.setEditable(false);
        StatusFujifilmX100VI_TEXTFIELD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StatusFujifilmX100VI_TEXTFIELD.setText("avaliable");
        StatusFujifilmX100VI_TEXTFIELD.addActionListener(this::StatusFujifilmX100VI_TEXTFIELDActionPerformed);

        PriceFujifilmX100VI_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        PriceFujifilmX100VI_LABEL.setText("1,000 THB /day");

        Spec1FujifilmX100VI_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Spec1FujifilmX100VI_LABEL.setText("Camera with 23mm F2 lens, X-Trans CMOS 5 HR ");

        Spec2FujifilmX100VI_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Spec2FujifilmX100VI_LABEL.setText("sensor, 40.2 megapixel resolution, and Film ");

        ConfirmPriceFujifilmX100VI_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmPriceFujifilmX100VI_LABEL.setText("Price per day");

        ConfirmPrice_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmPrice_LABEL.setText("1,900 THB");

        ConfirmDayFujifilmX100VI_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmDayFujifilmX100VI_LABEL.setText("number of days");

        DayFujifilmX100VI_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DayFujifilmX100VI_LABEL.setText("1 day");

        TotalFujifilmX100VI_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TotalFujifilmX100VI_LABEL.setText("Total");

        RealTotalFujifilmX100VI_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RealTotalFujifilmX100VI_LABEL.setText("1,900 THB");

        ConfirmRentFujifilmX100VI_BUTTON.setText("Confirm rental");
        ConfirmRentFujifilmX100VI_BUTTON.addActionListener(this::ConfirmRentFujifilmX100VI_BUTTONActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BacktToFujifilm_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ConfirmPriceFujifilmX100VI_LABEL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalFujifilmX100VI_LABEL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ConfirmDayFujifilmX100VI_LABEL, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RealTotalFujifilmX100VI_LABEL)
                                    .addComponent(DayFujifilmX100VI_LABEL)
                                    .addComponent(ConfirmPrice_LABEL))
                                .addGap(30, 30, 30))
                            .addComponent(Spec2FujifilmX100VI_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PriceFujifilmX100VI_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FujifilmX100VI_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(StatusFujifilmX100VI_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(ConfirmRentFujifilmX100VI_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Spec1FujifilmX100VI_LABEL))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(8, 8, 8))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(FujifilmX100VI_PIC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BacktToFujifilm_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FujifilmX100VI_PIC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FujifilmX100VI_LABEL)
                    .addComponent(StatusFujifilmX100VI_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PriceFujifilmX100VI_LABEL)
                .addGap(28, 28, 28)
                .addComponent(Spec1FujifilmX100VI_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Spec2FujifilmX100VI_LABEL)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPriceFujifilmX100VI_LABEL)
                    .addComponent(ConfirmPrice_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmDayFujifilmX100VI_LABEL)
                    .addComponent(DayFujifilmX100VI_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalFujifilmX100VI_LABEL)
                    .addComponent(RealTotalFujifilmX100VI_LABEL))
                .addGap(53, 53, 53)
                .addComponent(ConfirmRentFujifilmX100VI_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BacktToFujifilm_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacktToFujifilm_BUTTONActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentFujiFilm());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_BacktToFujifilm_BUTTONActionPerformed

    private void StatusFujifilmX100VI_TEXTFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusFujifilmX100VI_TEXTFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusFujifilmX100VI_TEXTFIELDActionPerformed

    private void ConfirmRentFujifilmX100VI_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmRentFujifilmX100VI_BUTTONActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new ConfirmRent());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_ConfirmRentFujifilmX100VI_BUTTONActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private guicamrent.RoundButton BacktToFujifilm_BUTTON;
    private javax.swing.JLabel ConfirmDayFujifilmX100VI_LABEL;
    private javax.swing.JLabel ConfirmPriceFujifilmX100VI_LABEL;
    private javax.swing.JLabel ConfirmPrice_LABEL;
    private guicamrent.RoundButton ConfirmRentFujifilmX100VI_BUTTON;
    private javax.swing.JLabel DayFujifilmX100VI_LABEL;
    private javax.swing.JLabel FujifilmX100VI_LABEL;
    private javax.swing.JLabel FujifilmX100VI_PIC;
    private javax.swing.JLabel PriceFujifilmX100VI_LABEL;
    private javax.swing.JLabel RealTotalFujifilmX100VI_LABEL;
    private javax.swing.JLabel Spec1FujifilmX100VI_LABEL;
    private javax.swing.JLabel Spec2FujifilmX100VI_LABEL;
    private guicamrent.RoundTextField StatusFujifilmX100VI_TEXTFIELD;
    private javax.swing.JLabel TotalFujifilmX100VI_LABEL;
    // End of variables declaration//GEN-END:variables
}
