/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guicamrent;

/**
 *
 * @author natth
 */
public class ConfirmPanasonicLumixS9 extends javax.swing.JPanel {

    /**
     * Creates new form ConfirmFujiFilmGFX100s
     */
    public ConfirmPanasonicLumixS9() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackToPanasonic_BUTTON = new guicamrent.RoundButton();
        PanasonicLumixS9_PIC = new javax.swing.JLabel();
        PanasonicLumixS9_LABEL = new javax.swing.JLabel();
        StatusPanasonicLumixS9_LABEL = new guicamrent.RoundTextField();
        PricePanasonicLumixS9_LABEL = new javax.swing.JLabel();
        Spec1PanasonicLumixS9_LABEL = new javax.swing.JLabel();
        Spec2PanasonicLumixS9_LABEL = new javax.swing.JLabel();
        ConfirmPricePanasonicLumixS9_LABEL = new javax.swing.JLabel();
        ConfirmPrice_LABEL = new javax.swing.JLabel();
        ConfirmDayPanasonicLumixS9_LABEL = new javax.swing.JLabel();
        DayPanasonicLumixS9_LABEL = new javax.swing.JLabel();
        TotalPanasonicLumixS9_LABEL = new javax.swing.JLabel();
        RealTotalPanasonicLumixS9_LABE = new javax.swing.JLabel();
        ConfirmRentPanasonicLumixS9_LABEL = new guicamrent.RoundButton();

        setBackground(new java.awt.Color(255, 255, 255));

        BackToPanasonic_BUTTON.setText("←");
        BackToPanasonic_BUTTON.addActionListener(this::BackToPanasonic_BUTTONActionPerformed);

        PanasonicLumixS9_PIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CAMPICresize/panasonic-lumix-s9.jpg"))); // NOI18N

        PanasonicLumixS9_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PanasonicLumixS9_LABEL.setText("Panasonic Lumix S9");

        StatusPanasonicLumixS9_LABEL.setEditable(false);
        StatusPanasonicLumixS9_LABEL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StatusPanasonicLumixS9_LABEL.setText("avaliable");
        StatusPanasonicLumixS9_LABEL.addActionListener(this::StatusPanasonicLumixS9_LABELActionPerformed);

        PricePanasonicLumixS9_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        PricePanasonicLumixS9_LABEL.setText("950 THB /day");

        Spec1PanasonicLumixS9_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Spec1PanasonicLumixS9_LABEL.setText("Full-Frame sensor, 24.2MP resolution");

        Spec2PanasonicLumixS9_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Spec2PanasonicLumixS9_LABEL.setText("5-axis IBIS image stabilization with 6.5 stops");

        ConfirmPricePanasonicLumixS9_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmPricePanasonicLumixS9_LABEL.setText("Price per day");

        ConfirmPrice_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmPrice_LABEL.setText("950 THB");

        ConfirmDayPanasonicLumixS9_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmDayPanasonicLumixS9_LABEL.setText("number of days");

        DayPanasonicLumixS9_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DayPanasonicLumixS9_LABEL.setText("1 day");

        TotalPanasonicLumixS9_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TotalPanasonicLumixS9_LABEL.setText("Total");

        RealTotalPanasonicLumixS9_LABE.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RealTotalPanasonicLumixS9_LABE.setText("950 THB");

        ConfirmRentPanasonicLumixS9_LABEL.setText("Confirm rental");
        ConfirmRentPanasonicLumixS9_LABEL.addActionListener(this::ConfirmRentPanasonicLumixS9_LABELActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackToPanasonic_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ConfirmPricePanasonicLumixS9_LABEL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalPanasonicLumixS9_LABEL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ConfirmDayPanasonicLumixS9_LABEL, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RealTotalPanasonicLumixS9_LABE)
                                    .addComponent(DayPanasonicLumixS9_LABEL)
                                    .addComponent(ConfirmPrice_LABEL))
                                .addGap(30, 30, 30))
                            .addComponent(Spec2PanasonicLumixS9_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PricePanasonicLumixS9_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(ConfirmRentPanasonicLumixS9_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Spec1PanasonicLumixS9_LABEL)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PanasonicLumixS9_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(StatusPanasonicLumixS9_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(8, 8, 8))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(PanasonicLumixS9_PIC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackToPanasonic_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanasonicLumixS9_PIC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PanasonicLumixS9_LABEL)
                    .addComponent(StatusPanasonicLumixS9_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PricePanasonicLumixS9_LABEL)
                .addGap(28, 28, 28)
                .addComponent(Spec1PanasonicLumixS9_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Spec2PanasonicLumixS9_LABEL)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPricePanasonicLumixS9_LABEL)
                    .addComponent(ConfirmPrice_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmDayPanasonicLumixS9_LABEL)
                    .addComponent(DayPanasonicLumixS9_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalPanasonicLumixS9_LABEL)
                    .addComponent(RealTotalPanasonicLumixS9_LABE))
                .addGap(53, 53, 53)
                .addComponent(ConfirmRentPanasonicLumixS9_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackToPanasonic_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToPanasonic_BUTTONActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentPanasonic());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_BackToPanasonic_BUTTONActionPerformed

    private void StatusPanasonicLumixS9_LABELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusPanasonicLumixS9_LABELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusPanasonicLumixS9_LABELActionPerformed

    private void ConfirmRentPanasonicLumixS9_LABELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmRentPanasonicLumixS9_LABELActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new ConfirmRent());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_ConfirmRentPanasonicLumixS9_LABELActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private guicamrent.RoundButton BackToPanasonic_BUTTON;
    private javax.swing.JLabel ConfirmDayPanasonicLumixS9_LABEL;
    private javax.swing.JLabel ConfirmPricePanasonicLumixS9_LABEL;
    private javax.swing.JLabel ConfirmPrice_LABEL;
    private guicamrent.RoundButton ConfirmRentPanasonicLumixS9_LABEL;
    private javax.swing.JLabel DayPanasonicLumixS9_LABEL;
    private javax.swing.JLabel PanasonicLumixS9_LABEL;
    private javax.swing.JLabel PanasonicLumixS9_PIC;
    private javax.swing.JLabel PricePanasonicLumixS9_LABEL;
    private javax.swing.JLabel RealTotalPanasonicLumixS9_LABE;
    private javax.swing.JLabel Spec1PanasonicLumixS9_LABEL;
    private javax.swing.JLabel Spec2PanasonicLumixS9_LABEL;
    private guicamrent.RoundTextField StatusPanasonicLumixS9_LABEL;
    private javax.swing.JLabel TotalPanasonicLumixS9_LABEL;
    // End of variables declaration//GEN-END:variables
}
