/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guicamrent;

/**
 *
 * @author natth
 */
public class ConfirmCanonEOSR6MarkII extends javax.swing.JPanel {

    /**
     * Creates new form ConfirmFujiFilmGFX100s
     */
    public ConfirmCanonEOSR6MarkII() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackToCanon_BUTTON = new guicamrent.RoundButton();
        CanonEOSR6MarkII_PIC = new javax.swing.JLabel();
        CanonEOSR6MarkII_LABEL = new javax.swing.JLabel();
        StatusCanonEOSR6MarkII_TEXTFIELD = new guicamrent.RoundTextField();
        PriceCanonEOSR6MarkII_LABEL = new javax.swing.JLabel();
        Spec1CanonEOSR6MarkII_LABEL = new javax.swing.JLabel();
        Spec2CanonEOSR6MarkII_LABEL = new javax.swing.JLabel();
        ConfirmPriceCanonEOSR6MarkII_LABEL = new javax.swing.JLabel();
        ConfirmPrice_LABEL = new javax.swing.JLabel();
        ConfirmDayCanonEOSR6MarkII_LABEL = new javax.swing.JLabel();
        DayCanonEOSR6MarkII_LABEL = new javax.swing.JLabel();
        TotalCanonEOSR6MarkII_LABEL = new javax.swing.JLabel();
        RealTotalCanonEOSR6MarkII_LABEL = new javax.swing.JLabel();
        ConfirmRentCanonEOSR6MarkII_BUTTON = new guicamrent.RoundButton();

        setBackground(new java.awt.Color(255, 255, 255));

        BackToCanon_BUTTON.setText("←");
        BackToCanon_BUTTON.addActionListener(this::BackToCanon_BUTTONActionPerformed);

        CanonEOSR6MarkII_PIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CAMPICresize/canon-r6-mkii.jpg"))); // NOI18N

        CanonEOSR6MarkII_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CanonEOSR6MarkII_LABEL.setText("Canon EOS R6 Mark II");

        StatusCanonEOSR6MarkII_TEXTFIELD.setEditable(false);
        StatusCanonEOSR6MarkII_TEXTFIELD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StatusCanonEOSR6MarkII_TEXTFIELD.setText("avaliable");
        StatusCanonEOSR6MarkII_TEXTFIELD.addActionListener(this::StatusCanonEOSR6MarkII_TEXTFIELDActionPerformed);

        PriceCanonEOSR6MarkII_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        PriceCanonEOSR6MarkII_LABEL.setText("1,300 THB /day");

        Spec1CanonEOSR6MarkII_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Spec1CanonEOSR6MarkII_LABEL.setText("24.2MP Full-Frame CMOS sensor");

        Spec2CanonEOSR6MarkII_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Spec2CanonEOSR6MarkII_LABEL.setText("4K60 10-bit internal video recording and C-Log 3");

        ConfirmPriceCanonEOSR6MarkII_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmPriceCanonEOSR6MarkII_LABEL.setText("Price per day");

        ConfirmPrice_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmPrice_LABEL.setText("1,300 THB");

        ConfirmDayCanonEOSR6MarkII_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmDayCanonEOSR6MarkII_LABEL.setText("number of days");

        DayCanonEOSR6MarkII_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DayCanonEOSR6MarkII_LABEL.setText("1 day");

        TotalCanonEOSR6MarkII_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TotalCanonEOSR6MarkII_LABEL.setText("Total");

        RealTotalCanonEOSR6MarkII_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RealTotalCanonEOSR6MarkII_LABEL.setText("1,300 THB");

        ConfirmRentCanonEOSR6MarkII_BUTTON.setText("Confirm rental");
        ConfirmRentCanonEOSR6MarkII_BUTTON.addActionListener(this::ConfirmRentCanonEOSR6MarkII_BUTTONActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackToCanon_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ConfirmPriceCanonEOSR6MarkII_LABEL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalCanonEOSR6MarkII_LABEL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ConfirmDayCanonEOSR6MarkII_LABEL, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RealTotalCanonEOSR6MarkII_LABEL)
                                    .addComponent(DayCanonEOSR6MarkII_LABEL)
                                    .addComponent(ConfirmPrice_LABEL))
                                .addGap(30, 30, 30))
                            .addComponent(Spec2CanonEOSR6MarkII_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PriceCanonEOSR6MarkII_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(ConfirmRentCanonEOSR6MarkII_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Spec1CanonEOSR6MarkII_LABEL)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CanonEOSR6MarkII_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(StatusCanonEOSR6MarkII_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(8, 8, 8))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(CanonEOSR6MarkII_PIC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackToCanon_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CanonEOSR6MarkII_PIC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CanonEOSR6MarkII_LABEL)
                    .addComponent(StatusCanonEOSR6MarkII_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PriceCanonEOSR6MarkII_LABEL)
                .addGap(28, 28, 28)
                .addComponent(Spec1CanonEOSR6MarkII_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Spec2CanonEOSR6MarkII_LABEL)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPriceCanonEOSR6MarkII_LABEL)
                    .addComponent(ConfirmPrice_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmDayCanonEOSR6MarkII_LABEL)
                    .addComponent(DayCanonEOSR6MarkII_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalCanonEOSR6MarkII_LABEL)
                    .addComponent(RealTotalCanonEOSR6MarkII_LABEL))
                .addGap(53, 53, 53)
                .addComponent(ConfirmRentCanonEOSR6MarkII_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackToCanon_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToCanon_BUTTONActionPerformed
            java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentCanon());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_BackToCanon_BUTTONActionPerformed

    private void StatusCanonEOSR6MarkII_TEXTFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusCanonEOSR6MarkII_TEXTFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusCanonEOSR6MarkII_TEXTFIELDActionPerformed

    private void ConfirmRentCanonEOSR6MarkII_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmRentCanonEOSR6MarkII_BUTTONActionPerformed
            java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new ConfirmRent());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_ConfirmRentCanonEOSR6MarkII_BUTTONActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private guicamrent.RoundButton BackToCanon_BUTTON;
    private javax.swing.JLabel CanonEOSR6MarkII_LABEL;
    private javax.swing.JLabel CanonEOSR6MarkII_PIC;
    private javax.swing.JLabel ConfirmDayCanonEOSR6MarkII_LABEL;
    private javax.swing.JLabel ConfirmPriceCanonEOSR6MarkII_LABEL;
    private javax.swing.JLabel ConfirmPrice_LABEL;
    private guicamrent.RoundButton ConfirmRentCanonEOSR6MarkII_BUTTON;
    private javax.swing.JLabel DayCanonEOSR6MarkII_LABEL;
    private javax.swing.JLabel PriceCanonEOSR6MarkII_LABEL;
    private javax.swing.JLabel RealTotalCanonEOSR6MarkII_LABEL;
    private javax.swing.JLabel Spec1CanonEOSR6MarkII_LABEL;
    private javax.swing.JLabel Spec2CanonEOSR6MarkII_LABEL;
    private guicamrent.RoundTextField StatusCanonEOSR6MarkII_TEXTFIELD;
    private javax.swing.JLabel TotalCanonEOSR6MarkII_LABEL;
    // End of variables declaration//GEN-END:variables
}
