/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guicamrent;

/**
 *
 * @author natth
 */
public class ConfirmSonyZVE10 extends javax.swing.JPanel {

    /**
     * Creates new form ConfirmFujiFilmGFX100s
     */
    public ConfirmSonyZVE10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackToSony_BUTTON = new guicamrent.RoundButton();
        SonyZVE10_PIC = new javax.swing.JLabel();
        SonyZVE10_LABEL = new javax.swing.JLabel();
        StatusSonyZVE10_TEXTFIELD = new guicamrent.RoundTextField();
        PriceSonyZVE10_LABEL = new javax.swing.JLabel();
        Spec1SonyZVE10_LABEL = new javax.swing.JLabel();
        Spec2SonyZVE10_LABEL = new javax.swing.JLabel();
        ConfirmPriceSonyZVE10_LABEL = new javax.swing.JLabel();
        ConfirmPrice_LABEL = new javax.swing.JLabel();
        ConfirmDaySonyZVE10_LABEL = new javax.swing.JLabel();
        DaySonyZVE10_LABEL = new javax.swing.JLabel();
        TotalSonyZVE10_LABEL = new javax.swing.JLabel();
        RealTotalSonyZVE10_LABEL = new javax.swing.JLabel();
        ConfirmRentSonyZVE10_BUTTON = new guicamrent.RoundButton();

        setBackground(new java.awt.Color(255, 255, 255));

        BackToSony_BUTTON.setText("←");
        BackToSony_BUTTON.addActionListener(this::BackToSony_BUTTONActionPerformed);

        SonyZVE10_PIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CAMPICresize/sony-zv-e10.jpg"))); // NOI18N

        SonyZVE10_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SonyZVE10_LABEL.setText("Sony ZV-E10 + Lens ");

        StatusSonyZVE10_TEXTFIELD.setEditable(false);
        StatusSonyZVE10_TEXTFIELD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StatusSonyZVE10_TEXTFIELD.setText("avaliable");
        StatusSonyZVE10_TEXTFIELD.addActionListener(this::StatusSonyZVE10_TEXTFIELDActionPerformed);

        PriceSonyZVE10_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        PriceSonyZVE10_LABEL.setText("500 THB /day");

        Spec1SonyZVE10_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Spec1SonyZVE10_LABEL.setText("24.2 million pixel APS-C Mirrorless Camera");

        Spec2SonyZVE10_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Spec2SonyZVE10_LABEL.setText("Realtime Eye AF Focus System and 4k Video.");

        ConfirmPriceSonyZVE10_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmPriceSonyZVE10_LABEL.setText("Price per day");

        ConfirmPrice_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmPrice_LABEL.setText("500 THB");

        ConfirmDaySonyZVE10_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmDaySonyZVE10_LABEL.setText("number of days");

        DaySonyZVE10_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DaySonyZVE10_LABEL.setText("1 day");

        TotalSonyZVE10_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TotalSonyZVE10_LABEL.setText("Total");

        RealTotalSonyZVE10_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RealTotalSonyZVE10_LABEL.setText("500 THB");

        ConfirmRentSonyZVE10_BUTTON.setText("Confirm rental");
        ConfirmRentSonyZVE10_BUTTON.addActionListener(this::ConfirmRentSonyZVE10_BUTTONActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackToSony_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ConfirmPriceSonyZVE10_LABEL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalSonyZVE10_LABEL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ConfirmDaySonyZVE10_LABEL, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RealTotalSonyZVE10_LABEL)
                                    .addComponent(DaySonyZVE10_LABEL)
                                    .addComponent(ConfirmPrice_LABEL))
                                .addGap(30, 30, 30))
                            .addComponent(Spec2SonyZVE10_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PriceSonyZVE10_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(ConfirmRentSonyZVE10_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Spec1SonyZVE10_LABEL)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SonyZVE10_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(StatusSonyZVE10_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(8, 8, 8))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(SonyZVE10_PIC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackToSony_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SonyZVE10_PIC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SonyZVE10_LABEL)
                    .addComponent(StatusSonyZVE10_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PriceSonyZVE10_LABEL)
                .addGap(28, 28, 28)
                .addComponent(Spec1SonyZVE10_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Spec2SonyZVE10_LABEL)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPriceSonyZVE10_LABEL)
                    .addComponent(ConfirmPrice_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmDaySonyZVE10_LABEL)
                    .addComponent(DaySonyZVE10_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalSonyZVE10_LABEL)
                    .addComponent(RealTotalSonyZVE10_LABEL))
                .addGap(53, 53, 53)
                .addComponent(ConfirmRentSonyZVE10_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackToSony_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToSony_BUTTONActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentSony());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_BackToSony_BUTTONActionPerformed

    private void StatusSonyZVE10_TEXTFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusSonyZVE10_TEXTFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusSonyZVE10_TEXTFIELDActionPerformed

    private void ConfirmRentSonyZVE10_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmRentSonyZVE10_BUTTONActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new ConfirmRent());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_ConfirmRentSonyZVE10_BUTTONActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private guicamrent.RoundButton BackToSony_BUTTON;
    private javax.swing.JLabel ConfirmDaySonyZVE10_LABEL;
    private javax.swing.JLabel ConfirmPriceSonyZVE10_LABEL;
    private javax.swing.JLabel ConfirmPrice_LABEL;
    private guicamrent.RoundButton ConfirmRentSonyZVE10_BUTTON;
    private javax.swing.JLabel DaySonyZVE10_LABEL;
    private javax.swing.JLabel PriceSonyZVE10_LABEL;
    private javax.swing.JLabel RealTotalSonyZVE10_LABEL;
    private javax.swing.JLabel SonyZVE10_LABEL;
    private javax.swing.JLabel SonyZVE10_PIC;
    private javax.swing.JLabel Spec1SonyZVE10_LABEL;
    private javax.swing.JLabel Spec2SonyZVE10_LABEL;
    private guicamrent.RoundTextField StatusSonyZVE10_TEXTFIELD;
    private javax.swing.JLabel TotalSonyZVE10_LABEL;
    // End of variables declaration//GEN-END:variables
}
