/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guicamrent;

/**
 *
 * @author natth
 */
public class ConfirmFujiFilmGFX100s extends javax.swing.JPanel {

    /**
     * Creates new form ConfirmFujiFilmGFX100s
     */
    public ConfirmFujiFilmGFX100s() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackToFujifilm_BUTTON = new guicamrent.RoundButton();
        FujifilmGFX100S_PIC = new javax.swing.JLabel();
        FujifilmGFX100S_LABEL = new javax.swing.JLabel();
        StatusFujifilmGFX100S_TEXTFIELD = new guicamrent.RoundTextField();
        PriceFujifilmGFX100S_LABEL = new javax.swing.JLabel();
        Spec1FujifilmGFX100S_LABEL = new javax.swing.JLabel();
        Spec2FujifilmGFX100S_LABEL = new javax.swing.JLabel();
        ConfirmPriceFujifilmGFX100S_LABEL = new javax.swing.JLabel();
        ConfirmPrice_LABEL = new javax.swing.JLabel();
        ConfirmDayFujifilmGFX100S_LABEL = new javax.swing.JLabel();
        DayFujifilmGFX100S_LABEL = new javax.swing.JLabel();
        TotalFujifilmGFX100S_LABEL = new javax.swing.JLabel();
        RealTotalFujifilmGFX100S_LABEL = new javax.swing.JLabel();
        ConfirmRentFujifilmGFX100S_BUTTON = new guicamrent.RoundButton();

        setBackground(new java.awt.Color(255, 255, 255));

        BackToFujifilm_BUTTON.setText("←");
        BackToFujifilm_BUTTON.addActionListener(this::BackToFujifilm_BUTTONActionPerformed);

        FujifilmGFX100S_PIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CAMPICresize/gfx-100s.jpg"))); // NOI18N

        FujifilmGFX100S_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        FujifilmGFX100S_LABEL.setText("Fujifilm GFX 100S");

        StatusFujifilmGFX100S_TEXTFIELD.setEditable(false);
        StatusFujifilmGFX100S_TEXTFIELD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StatusFujifilmGFX100S_TEXTFIELD.setText("avaliable");
        StatusFujifilmGFX100S_TEXTFIELD.addActionListener(this::StatusFujifilmGFX100S_TEXTFIELDActionPerformed);

        PriceFujifilmGFX100S_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        PriceFujifilmGFX100S_LABEL.setText("1,900 THB /day");

        Spec1FujifilmGFX100S_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Spec1FujifilmGFX100S_LABEL.setText("Medium format camera with 102MP ");

        Spec2FujifilmGFX100S_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Spec2FujifilmGFX100S_LABEL.setText("43.8 x 32.9mm BSI CMOS sensor");

        ConfirmPriceFujifilmGFX100S_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmPriceFujifilmGFX100S_LABEL.setText("Price per day");

        ConfirmPrice_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmPrice_LABEL.setText("1,900 THB");

        ConfirmDayFujifilmGFX100S_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmDayFujifilmGFX100S_LABEL.setText("number of days");

        DayFujifilmGFX100S_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DayFujifilmGFX100S_LABEL.setText("1 day");

        TotalFujifilmGFX100S_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TotalFujifilmGFX100S_LABEL.setText("Total");

        RealTotalFujifilmGFX100S_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RealTotalFujifilmGFX100S_LABEL.setText("1,900 THB");

        ConfirmRentFujifilmGFX100S_BUTTON.setText("Confirm rental");
        ConfirmRentFujifilmGFX100S_BUTTON.addActionListener(this::ConfirmRentFujifilmGFX100S_BUTTONActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackToFujifilm_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PriceFujifilmGFX100S_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FujifilmGFX100S_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(StatusFujifilmGFX100S_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Spec1FujifilmGFX100S_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ConfirmPriceFujifilmGFX100S_LABEL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalFujifilmGFX100S_LABEL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ConfirmDayFujifilmGFX100S_LABEL, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RealTotalFujifilmGFX100S_LABEL)
                                    .addComponent(DayFujifilmGFX100S_LABEL)
                                    .addComponent(ConfirmPrice_LABEL))
                                .addGap(30, 30, 30))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ConfirmRentFujifilmGFX100S_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Spec2FujifilmGFX100S_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(8, 8, 8))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(FujifilmGFX100S_PIC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackToFujifilm_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FujifilmGFX100S_PIC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FujifilmGFX100S_LABEL)
                    .addComponent(StatusFujifilmGFX100S_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PriceFujifilmGFX100S_LABEL)
                .addGap(28, 28, 28)
                .addComponent(Spec1FujifilmGFX100S_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Spec2FujifilmGFX100S_LABEL)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPriceFujifilmGFX100S_LABEL)
                    .addComponent(ConfirmPrice_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmDayFujifilmGFX100S_LABEL)
                    .addComponent(DayFujifilmGFX100S_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalFujifilmGFX100S_LABEL)
                    .addComponent(RealTotalFujifilmGFX100S_LABEL))
                .addGap(53, 53, 53)
                .addComponent(ConfirmRentFujifilmGFX100S_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackToFujifilm_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToFujifilm_BUTTONActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentFujiFilm());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_BackToFujifilm_BUTTONActionPerformed

    private void StatusFujifilmGFX100S_TEXTFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusFujifilmGFX100S_TEXTFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusFujifilmGFX100S_TEXTFIELDActionPerformed

    private void ConfirmRentFujifilmGFX100S_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmRentFujifilmGFX100S_BUTTONActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new ConfirmRent());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_ConfirmRentFujifilmGFX100S_BUTTONActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private guicamrent.RoundButton BackToFujifilm_BUTTON;
    private javax.swing.JLabel ConfirmDayFujifilmGFX100S_LABEL;
    private javax.swing.JLabel ConfirmPriceFujifilmGFX100S_LABEL;
    private javax.swing.JLabel ConfirmPrice_LABEL;
    private guicamrent.RoundButton ConfirmRentFujifilmGFX100S_BUTTON;
    private javax.swing.JLabel DayFujifilmGFX100S_LABEL;
    private javax.swing.JLabel FujifilmGFX100S_LABEL;
    private javax.swing.JLabel FujifilmGFX100S_PIC;
    private javax.swing.JLabel PriceFujifilmGFX100S_LABEL;
    private javax.swing.JLabel RealTotalFujifilmGFX100S_LABEL;
    private javax.swing.JLabel Spec1FujifilmGFX100S_LABEL;
    private javax.swing.JLabel Spec2FujifilmGFX100S_LABEL;
    private guicamrent.RoundTextField StatusFujifilmGFX100S_TEXTFIELD;
    private javax.swing.JLabel TotalFujifilmGFX100S_LABEL;
    // End of variables declaration//GEN-END:variables
}
