/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guicamrent;

/**
 *
 * @author natth
 */
public class ConfirmSonyA7V extends javax.swing.JPanel {

    /**
     * Creates new form ConfirmFujiFilmGFX100s
     */
    public ConfirmSonyA7V() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackToSony_BUTTON = new guicamrent.RoundButton();
        SonyA7V_PIC = new javax.swing.JLabel();
        SonyA7V_LABEL = new javax.swing.JLabel();
        StatusSonyA7V_TEXTFIELD = new guicamrent.RoundTextField();
        PriceSonyA7V_LABEL = new javax.swing.JLabel();
        Spec1SonyA7V_LABEL = new javax.swing.JLabel();
        Spec2SonyA7V_LABEL = new javax.swing.JLabel();
        ConfirmPriceSonyA7V_LABEL = new javax.swing.JLabel();
        ConfirPrice_LABEL = new javax.swing.JLabel();
        ConfirmDaySonyA7V_LABEL = new javax.swing.JLabel();
        DaySonyA7V_LABEL = new javax.swing.JLabel();
        TotalSonyA7V_LABEL = new javax.swing.JLabel();
        RealTotalSonyA7V_LABEL = new javax.swing.JLabel();
        ConfirmRentSonyA7V_LABEL = new guicamrent.RoundButton();

        setBackground(new java.awt.Color(255, 255, 255));

        BackToSony_BUTTON.setText("←");
        BackToSony_BUTTON.addActionListener(this::BackToSony_BUTTONActionPerformed);

        SonyA7V_PIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CAMPICresize/sony-a7v.jpg"))); // NOI18N

        SonyA7V_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SonyA7V_LABEL.setText("Sony A7V");

        StatusSonyA7V_TEXTFIELD.setEditable(false);
        StatusSonyA7V_TEXTFIELD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StatusSonyA7V_TEXTFIELD.setText("avaliable");
        StatusSonyA7V_TEXTFIELD.addActionListener(this::StatusSonyA7V_TEXTFIELDActionPerformed);

        PriceSonyA7V_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        PriceSonyA7V_LABEL.setText("1,400 THB /day");

        Spec1SonyA7V_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Spec1SonyA7V_LABEL.setText("35mm full-frame camera, 33MP ");

        Spec2SonyA7V_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Spec2SonyA7V_LABEL.setText("Partially-Stacked Exmor RS Sensor, AI ");

        ConfirmPriceSonyA7V_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmPriceSonyA7V_LABEL.setText("Price per day");

        ConfirPrice_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirPrice_LABEL.setText("1,400 THB");

        ConfirmDaySonyA7V_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ConfirmDaySonyA7V_LABEL.setText("number of days");

        DaySonyA7V_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DaySonyA7V_LABEL.setText("1 day");

        TotalSonyA7V_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TotalSonyA7V_LABEL.setText("Total");

        RealTotalSonyA7V_LABEL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RealTotalSonyA7V_LABEL.setText("1,400 THB");

        ConfirmRentSonyA7V_LABEL.setText("Confirm rental");
        ConfirmRentSonyA7V_LABEL.addActionListener(this::ConfirmRentSonyA7V_LABELActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackToSony_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ConfirmPriceSonyA7V_LABEL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalSonyA7V_LABEL, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ConfirmDaySonyA7V_LABEL, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RealTotalSonyA7V_LABEL)
                                    .addComponent(DaySonyA7V_LABEL)
                                    .addComponent(ConfirPrice_LABEL))
                                .addGap(30, 30, 30))
                            .addComponent(Spec2SonyA7V_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PriceSonyA7V_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(ConfirmRentSonyA7V_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Spec1SonyA7V_LABEL)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SonyA7V_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(StatusSonyA7V_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(8, 8, 8))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(SonyA7V_PIC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackToSony_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SonyA7V_PIC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SonyA7V_LABEL)
                    .addComponent(StatusSonyA7V_TEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PriceSonyA7V_LABEL)
                .addGap(28, 28, 28)
                .addComponent(Spec1SonyA7V_LABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Spec2SonyA7V_LABEL)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPriceSonyA7V_LABEL)
                    .addComponent(ConfirPrice_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmDaySonyA7V_LABEL)
                    .addComponent(DaySonyA7V_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalSonyA7V_LABEL)
                    .addComponent(RealTotalSonyA7V_LABEL))
                .addGap(53, 53, 53)
                .addComponent(ConfirmRentSonyA7V_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackToSony_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToSony_BUTTONActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentSony());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_BackToSony_BUTTONActionPerformed

    private void StatusSonyA7V_TEXTFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusSonyA7V_TEXTFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusSonyA7V_TEXTFIELDActionPerformed

    private void ConfirmRentSonyA7V_LABELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmRentSonyA7V_LABELActionPerformed
                    java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new ConfirmRent());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_ConfirmRentSonyA7V_LABELActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private guicamrent.RoundButton BackToSony_BUTTON;
    private javax.swing.JLabel ConfirPrice_LABEL;
    private javax.swing.JLabel ConfirmDaySonyA7V_LABEL;
    private javax.swing.JLabel ConfirmPriceSonyA7V_LABEL;
    private guicamrent.RoundButton ConfirmRentSonyA7V_LABEL;
    private javax.swing.JLabel DaySonyA7V_LABEL;
    private javax.swing.JLabel PriceSonyA7V_LABEL;
    private javax.swing.JLabel RealTotalSonyA7V_LABEL;
    private javax.swing.JLabel SonyA7V_LABEL;
    private javax.swing.JLabel SonyA7V_PIC;
    private javax.swing.JLabel Spec1SonyA7V_LABEL;
    private javax.swing.JLabel Spec2SonyA7V_LABEL;
    private guicamrent.RoundTextField StatusSonyA7V_TEXTFIELD;
    private javax.swing.JLabel TotalSonyA7V_LABEL;
    // End of variables declaration//GEN-END:variables
}
