/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guicamrent;

import MAIN.loginGUI;

/**
 *
 * @author msi thin15
 */
public class CreateAccount extends javax.swing.JPanel {

    public CreateAccount() {
        initComponents();
        addPlaceholder(roundTextField7, "Username");
        addPlaceholder(roundTextField9, "Phone");
        addPlaceholder(roundTextField10, "Email");
        addPlaceholder(roundTextField11, "Password");
        addPlaceholder(roundTextField12, "Confirmed Password");
    }

    /** ล้างข้อความตัวอย่างเมื่อคลิกช่อง และใส่กลับถ้าปล่อยว่าง */
    private void addPlaceholder(javax.swing.JTextField field, String placeholder) {
        field.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (field.getText().trim().isEmpty()) {
                    field.setText(placeholder);
                }
            }
        });
    }

    /** ค่าในช่องที่ไม่ใช่ข้อความตัวอย่าง */
    private String value(javax.swing.JTextField field, String placeholder) {
        String t = field.getText().trim();
        return t.equals(placeholder) ? "" : t;
    }

    private void warn(String msg) {
        javax.swing.JOptionPane.showMessageDialog(this, msg, "แจ้งเตือน",
                javax.swing.JOptionPane.WARNING_MESSAGE);
    }

    private void goToLogin() {
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
        loginGUI login = new loginGUI();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundButton2 = new guicamrent.RoundButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        roundTextField7 = new guicamrent.RoundTextField();
        roundTextField9 = new guicamrent.RoundTextField();
        roundTextField10 = new guicamrent.RoundTextField();
        roundTextField11 = new guicamrent.RoundTextField();
        roundTextField12 = new guicamrent.RoundTextField();
        SIGNUP_LABEL = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(380, 700));

        roundButton2.setText("sign Up");
        roundButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        roundButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roundButton2MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIPIC/logo (344x344 px).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Create Account");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIPIC/login (35x35 px).png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIPIC/call (35x35 px).png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIPIC/mail (33x33px).png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIPIC/lock (33x33px).png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIPIC/confirm lock (33x33px).png"))); // NOI18N

        roundTextField7.setText("Username");
        roundTextField7.addActionListener(this::roundTextField7ActionPerformed);

        roundTextField9.setText("Phone");

        roundTextField10.setText("Email");
        roundTextField10.addActionListener(this::roundTextField10ActionPerformed);

        roundTextField11.setText("Password");
        roundTextField11.addActionListener(this::roundTextField11ActionPerformed);

        roundTextField12.setText("Confirmed Password");
        roundTextField12.addActionListener(this::roundTextField12ActionPerformed);

        SIGNUP_LABEL.setForeground(new java.awt.Color(102, 153, 255));
        SIGNUP_LABEL.setText("Already have an account");
        SIGNUP_LABEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SIGNUP_LABELMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(roundTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(roundTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(roundTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(roundTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(roundTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SIGNUP_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(roundButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2)
                                                .addGap(42, 42, 42)
                                                .addComponent(jLabel4))
                                            .addComponent(roundTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(roundTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(roundTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(roundTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(roundTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(roundButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SIGNUP_LABEL)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void roundTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundTextField11ActionPerformed

    private void roundTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundTextField12ActionPerformed

    private void roundTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundTextField7ActionPerformed

    private void roundTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundTextField10ActionPerformed

    private void roundButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundButton2MouseClicked
        String username = value(roundTextField7, "Username");
        String phone = value(roundTextField9, "Phone");
        String email = value(roundTextField10, "Email");
        String password = value(roundTextField11, "Password");
        String confirm = value(roundTextField12, "Confirmed Password");

        if (username.isEmpty() || phone.isEmpty() || email.isEmpty()
                || password.isEmpty() || confirm.isEmpty()) {
            warn("กรุณากรอกข้อมูลให้ครบทุกช่อง");
            return;
        }
        if (username.contains(",") || phone.contains(",") || email.contains(",") || password.contains(",")) {
            warn("ห้ามใช้เครื่องหมายจุลภาค (,) ในข้อมูล");
            return;
        }
        if (!phone.matches("\\d{9,10}")) {
            warn("เบอร์โทรต้องเป็นตัวเลข 9-10 หลัก");
            return;
        }
        if (!email.matches("^[\\w.+-]+@[\\w-]+(\\.[\\w-]+)+$")) {
            warn("รูปแบบ Email ไม่ถูกต้อง");
            return;
        }
        if (!password.equals(confirm)) {
            warn("Password และ Confirmed Password ไม่ตรงกัน");
            return;
        }
        if (UserDatabase.userExists(username)) {
            warn("Username นี้ถูกใช้งานแล้ว");
            return;
        }

        if (UserDatabase.saveUser(username, password, phone, email)) {
            javax.swing.JOptionPane.showMessageDialog(this, "สมัครสมาชิกสำเร็จ!", "Success",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            goToLogin();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "ไม่สามารถบันทึกข้อมูลได้", "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_roundButton2MouseClicked

    private void SIGNUP_LABELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIGNUP_LABELMouseClicked
        goToLogin();
    }//GEN-LAST:event_SIGNUP_LABELMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SIGNUP_LABEL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private guicamrent.RoundButton roundButton2;
    private guicamrent.RoundTextField roundTextField10;
    private guicamrent.RoundTextField roundTextField11;
    private guicamrent.RoundTextField roundTextField12;
    private guicamrent.RoundTextField roundTextField7;
    private guicamrent.RoundTextField roundTextField9;
    // End of variables declaration//GEN-END:variables
}