/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package guicamrent;

import java.awt.Color;

/**
 *
 * @author natth
 */
public class Date_Time extends javax.swing.JPanel {

    /**
     * Creates new form Date_Time
     */
    public Date_Time() {
        initComponents();     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CheckCAM_Button = new guicamrent.RoundButton();
        displaycamWarn = new javax.swing.JLabel();
        Returndate_Label = new javax.swing.JLabel();
        ReturnMonth_COMBOBOX = new javax.swing.JComboBox<>();
        PickupDay_COMBOBOX = new javax.swing.JComboBox<>();
        PickupMonth_COMBOBOX = new javax.swing.JComboBox<>();
        ReturnDay_COMBOBOX = new javax.swing.JComboBox<>();
        PickUpDate = new javax.swing.JLabel();
        LocationGetBack = new javax.swing.JLabel();
        LOGO = new javax.swing.JLabel();
        LINER1 = new javax.swing.JLabel();
        LINER2 = new javax.swing.JLabel();
        LINER3 = new javax.swing.JLabel();
        Location_ButtonGreyStatic = new guicamrent.RoundButton_GreyStatic();
        PickupDay_ButtonGreyStatic = new guicamrent.RoundButton_GreyStatic();
        PickupMonth_ButtonGreyStatic = new guicamrent.RoundButton_GreyStatic();
        ReturnMonth_ButtonGreyStatic = new guicamrent.RoundButton_GreyStatic();
        ReturnDay_ButtonGreyStatic = new guicamrent.RoundButton_GreyStatic();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(380, 700));

        CheckCAM_Button.setText("Check Camera");
        CheckCAM_Button.addActionListener(this::CheckCAM_ButtonActionPerformed);

        displaycamWarn.setText("Only available cameras for your selected dates will be displayed");

        Returndate_Label.setText("Returndate");

        ReturnMonth_COMBOBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        ReturnMonth_COMBOBOX.addActionListener(this::ReturnMonth_COMBOBOXActionPerformed);

        PickupDay_COMBOBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        PickupDay_COMBOBOX.addActionListener(this::PickupDay_COMBOBOXActionPerformed);

        PickupMonth_COMBOBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        PickupMonth_COMBOBOX.addActionListener(this::PickupMonth_COMBOBOXActionPerformed);

        ReturnDay_COMBOBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        ReturnDay_COMBOBOX.addActionListener(this::ReturnDay_COMBOBOXActionPerformed);

        PickUpDate.setText("Pick up date");

        LocationGetBack.setText("Location Get it back");

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIPIC/logo (344x344 px).png"))); // NOI18N
        LOGO.setText("jLabel1");

        LINER1.setText("_______________________________________________________________");

        LINER2.setText("_______________________________________________________________");

        LINER3.setText("_______________________________________________________________");

        Location_ButtonGreyStatic.setText("Kasetsart Kamphaeng Saen University");
        Location_ButtonGreyStatic.setEnabled(true);

        PickupDay_ButtonGreyStatic.setText("DAY");
        PickupDay_ButtonGreyStatic.setEnabled(true);
        PickupDay_ButtonGreyStatic.addActionListener(this::PickupDay_ButtonGreyStaticActionPerformed);

        PickupMonth_ButtonGreyStatic.setText("MONTH");
        PickupMonth_ButtonGreyStatic.setEnabled(true);
        PickupMonth_ButtonGreyStatic.addActionListener(this::PickupMonth_ButtonGreyStaticActionPerformed);

        ReturnMonth_ButtonGreyStatic.setText("MONTH");
        ReturnMonth_ButtonGreyStatic.setEnabled(true);
        ReturnMonth_ButtonGreyStatic.addActionListener(this::ReturnMonth_ButtonGreyStaticActionPerformed);

        ReturnDay_ButtonGreyStatic.setText("DAY");
        ReturnDay_ButtonGreyStatic.setEnabled(true);
        ReturnDay_ButtonGreyStatic.addActionListener(this::ReturnDay_ButtonGreyStaticActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(CheckCAM_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LocationGetBack, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PickupDay_ButtonGreyStatic, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PickupDay_COMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(PickupMonth_ButtonGreyStatic, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PickupMonth_COMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PickUpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displaycamWarn)
                            .addComponent(LINER1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LINER2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LINER3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Returndate_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(ReturnDay_ButtonGreyStatic, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ReturnDay_COMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(ReturnMonth_ButtonGreyStatic, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(ReturnMonth_COMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Location_ButtonGreyStatic, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LocationGetBack)
                .addGap(8, 8, 8)
                .addComponent(Location_ButtonGreyStatic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LINER1)
                .addGap(5, 5, 5)
                .addComponent(PickUpDate)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PickupDay_COMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PickupMonth_COMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PickupDay_ButtonGreyStatic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PickupMonth_ButtonGreyStatic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(LINER2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Returndate_Label)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReturnDay_COMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReturnMonth_COMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReturnMonth_ButtonGreyStatic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReturnDay_ButtonGreyStatic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(LINER3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(displaycamWarn)
                .addGap(26, 26, 26)
                .addComponent(CheckCAM_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnMonth_COMBOBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnMonth_COMBOBOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnMonth_COMBOBOXActionPerformed

    private void PickupDay_COMBOBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PickupDay_COMBOBOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PickupDay_COMBOBOXActionPerformed

    private void PickupMonth_COMBOBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PickupMonth_COMBOBOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PickupMonth_COMBOBOXActionPerformed

    private void ReturnDay_COMBOBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnDay_COMBOBOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnDay_COMBOBOXActionPerformed

    private void CheckCAM_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckCAM_ButtonActionPerformed
            java.awt.Window window =
            javax.swing.SwingUtilities.getWindowAncestor(this);

    if (window instanceof javax.swing.JFrame) {
        javax.swing.JFrame frame = (javax.swing.JFrame) window;
        frame.setContentPane(new CamrentSony());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.revalidate();
        frame.repaint();
    }
    }//GEN-LAST:event_CheckCAM_ButtonActionPerformed

    private void PickupDay_ButtonGreyStaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PickupDay_ButtonGreyStaticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PickupDay_ButtonGreyStaticActionPerformed

    private void PickupMonth_ButtonGreyStaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PickupMonth_ButtonGreyStaticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PickupMonth_ButtonGreyStaticActionPerformed

    private void ReturnMonth_ButtonGreyStaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnMonth_ButtonGreyStaticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnMonth_ButtonGreyStaticActionPerformed

    private void ReturnDay_ButtonGreyStaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnDay_ButtonGreyStaticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnDay_ButtonGreyStaticActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private guicamrent.RoundButton CheckCAM_Button;
    private javax.swing.JLabel LINER1;
    private javax.swing.JLabel LINER2;
    private javax.swing.JLabel LINER3;
    private javax.swing.JLabel LOGO;
    private javax.swing.JLabel LocationGetBack;
    private guicamrent.RoundButton_GreyStatic Location_ButtonGreyStatic;
    private javax.swing.JLabel PickUpDate;
    private guicamrent.RoundButton_GreyStatic PickupDay_ButtonGreyStatic;
    private javax.swing.JComboBox<String> PickupDay_COMBOBOX;
    private guicamrent.RoundButton_GreyStatic PickupMonth_ButtonGreyStatic;
    private javax.swing.JComboBox<String> PickupMonth_COMBOBOX;
    private guicamrent.RoundButton_GreyStatic ReturnDay_ButtonGreyStatic;
    private javax.swing.JComboBox<String> ReturnDay_COMBOBOX;
    private guicamrent.RoundButton_GreyStatic ReturnMonth_ButtonGreyStatic;
    private javax.swing.JComboBox<String> ReturnMonth_COMBOBOX;
    private javax.swing.JLabel Returndate_Label;
    private javax.swing.JLabel displaycamWarn;
    // End of variables declaration//GEN-END:variables
}
